services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inventory-sqlserver

    environment:
      SA_PASSWORD: "Admin123*"
      ACCEPT_EULA: "Y"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

  inventory-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: inventory-api

    depends_on:
      - sqlserver

    ports:
      - "8080:8080"

  inventory-client:
    build:
      context: .
      dockerfile: InventorySystem.Client/Dockerfile

    container_name: inventory-client

    depends_on:
      - inventory-api

    ports:
      - "8081:80"

volumes:
  sqlserver_data: